<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('items')->delete(); // Truncate the table first
        
        $items = [
            [
                "id" => "1968.94",
                "object" => "Lakonische Schale",
                "title" => "Randschale",
                "author" => "Reiter-Maler / Brümmer, Elfriede / Jagd-Maler / Shefton, Brian Benjamin",
                "description" => null,
                "material" => "Ton",
                "technique" => "schnell gedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Sphinx, Palmette (Ornament), Geflügel (Hahn, Henne, Huhn etc.)",
                "style" => "mittelarchaisch, Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/randschale/1968.94/dc00126479",
                "collection" => "Antike",
                "year_from" => "550 v. Chr.",
                "year_to" => "526 v. Chr.",
                "acquisition_date" => "19.06.1968",
                "year" => -550
            ],
            [
                "id" => "O1907.65",
                "object" => "Ornamentstich",
                "title" => "Zwei Säulen mit Bandelwerk, Blatt 5 aus der Folge \"Gantz Neu sehr nützl. Säulen und andern Ornamenten\"",
                "author" => "Bergmüller, Johann Andreas / Fridrich der Ältere, Jacob Andreas / Jeremias Wolff Erben",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Säule, Pfeiler (Architektur), Amoretten, Putten, Akanthusornament, Laub- und Bandelwerk, Skulptur, Plastik, Bildhauerkunst, Ornamente, symbolische Darstellungen, Allegorien und Embleme der Architektur (Architectura), Hammer, Wolken",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/zwei-saulen-mit-bandelwerk-blatt-5-aus-der-folge-gantz-neu-sehr-nutzl-saulen-und-andern-ornamenten/O1907.65/dc00106301",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730 / 1730 / 1730",
                "year_to" => "1738 / 1740 / 1740",
                "acquisition_date" => "1907",
                "year" => 1730
            ],
            [
                "id" => "O1910.155",
                "object" => "Ornamentstich",
                "title" => "Aus einer Folge: Der sechzehnte Teil einer Bordüre für eine festonnirte Schüssel, in der Mitte die Figur der Justitia in Einfassung",
                "author" => "Solis, Virgil",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung, Kupferstich",
                "iconography" => "Groteske (Ornament), Ornamente, Fabelwesen, Monster, legendäre Gestalten, Behälter, Löwe (Raubtiere), Justitia, Tiere als Ornament, Blumenornamente, Tierornamente, Maske (Maskaron)",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/aus-einer-folge-der-sechzehnte-teil-einer-bordure-fur-eine-festonnirte-schussel-in-der-mitte-die-fig/O1910.155/dc00101808",
                "collection" => "Grafische Sammlung",
                "year_from" => "1550",
                "year_to" => "1562",
                "acquisition_date" => "1910",
                "year" => 1550
            ],
            [
                "id" => "1906.97",
                "object" => "Tebako",
                "title" => "Kosmetikkasten (tebako 手箱) mit Flaschenkürbis-Ranken",
                "author" => "Ogata, Kōrin / Nagata Yūji (永田友治)",
                "description" => null,
                "material" => "Lack, Perlmutt, Holz, Blei",
                "technique" => "lackiert, intarsiert",
                "iconography" => "Rankenornament",
                "style" => "Edo-Zeit, Meiji-Zeit",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/kosmetikkasten-tebako-mit-flaschenkurbis-ranken/1906.97/dc00112424",
                "collection" => "Ostasien",
                "year_from" => "1851 / 1906",
                "year_to" => "1900",
                "acquisition_date" => "1906",
                "year" => 1851
            ],
            [
                "id" => "O1907.217",
                "object" => "Ornamentstich",
                "title" => "Standuhr auf breitem Sockel, Blatt aus einer Folge",
                "author" => "Hoppenhaupt der Ältere, Johann Michael",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Zeitmessung/Uhr, Rocaille, Fabeltiere, Kerze, Blumenornamente, Kunsthandwerk, Kunstgewerbe, Industriedesign",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/standuhr-auf-breitem-sockel-blatt-aus-einer-folge/O1907.217/dc00106425",
                "collection" => "Grafische Sammlung",
                "year_from" => "1740",
                "year_to" => "1750",
                "acquisition_date" => "1907",
                "year" => 1740
            ],
            [
                "id" => "EP2009.786",
                "object" => "Plakat",
                "title" => "Künstlerbund Hagen Eröffnungsausstellung Januar 1902",
                "author" => "Lefler, Heinrich / Christoph Reisser's Söhne / Künstlerbund Hagen",
                "description" => null,
                "material" => ", Papier",
                "technique" => "Lithografie",
                "iconography" => "Wappenschild, heraldisches Symbol, Girlanden, Blumengewinde (Ornament), Ornamente",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/kunstlerbund-hagen-eroffnungsausstellung-januar-1902/EP2009.786/dc00056632",
                "collection" => "Plakatsammlung",
                "year_from" => "1901 / 1901 / 1902",
                "year_to" => "1902 / 1902",
                "acquisition_date" => "",
                "year" => 1901
            ],
            [
                "id" => "1890.192",
                "object" => "Teller",
                "title" => "Teller (tagliere) mit der Personifikation der Pax (Friede)",
                "author" => "Grue, Carlo Antonio",
                "description" => null,
                "material" => "Majolika, Keramik",
                "technique" => "scheibengedreht, glasiert, bemalt (Keramik), gebrannt (Keramik)",
                "iconography" => "Personifikationen, Pax, Amoretten, Putten, Symbole, Allegorien des Friedens (Pax), Kartusche (Ornament), Maske (Maskaron)",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/teller-tagliere-mit-der-personifikation-der-pax-friede/1890.192/mkg-e00120351",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1696",
                "year_to" => "1705",
                "acquisition_date" => "",
                "year" => 1696
            ],
            [
                "id" => "1963.95",
                "object" => "Oinochoe",
                "title" => "Oinochoe Form I (Mädchen am Brunnenhaus)",
                "author" => "Hasselmann-Maler / Beazley, John D.",
                "description" => null,
                "material" => "Ton",
                "technique" => "schnell gedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "junge Frau, Mädchen, Brunnen, Wasser (Elemente), Gesellschaft/Zivilisation/Kultur, Eierstab",
                "style" => "Hochklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/oinochoe-form-i-madchen-am-brunnenhaus/1963.95/dc00126081",
                "collection" => "Antike",
                "year_from" => "440 v. Chr.",
                "year_to" => "430 v. Chr.",
                "acquisition_date" => "01.11.1963",
                "year" => -440
            ],
            [
                "id" => "O1911.548",
                "object" => "Ornamentstich",
                "title" => "Zwei Säulen und eine Skulptur, Blatt 6 aus der Folge \"Gantz Neu sehr nützl. Säulen und andern Ornamente\n",
                "author" => "Bergmüller, Johann Andreas / Fridrich der Ältere, Jacob Andreas / Jeremias Wolff Erben",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Säule, Pfeiler (Architektur), Amoretten, Putten, Altar, Laub- und Bandelwerk, Skulptur, Plastik, Bildhauerkunst, Ornamente, Heilige",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/zwei-saulen-und-eine-skulptur-blatt-6-aus-der-folge-gantz-neu-sehr-nutzl-saulen-und-andern-ornamente/O1911.548/dc00106304",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730 / 1730 / 1730",
                "year_to" => "1738 / 1740 / 1740",
                "acquisition_date" => "",
                "year" => 1730
            ],
            [
                "id" => "O1896.68",
                "object" => "Ornamentstich",
                "title" => "Runde mit Flechtwerk und Knoten",
                "author" => "Dürer, Albrecht",
                "description" => null,
                "material" => "Papier",
                "technique" => "Holzschnitt",
                "iconography" => "Pflanzenornamente, Flechtwerk (Ornament)",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/runde-mit-flechtwerk-und-knoten/O1896.68/dc00101635",
                "collection" => "Grafische Sammlung",
                "year_from" => "1500",
                "year_to" => "1528",
                "acquisition_date" => "1896",
                "year" => 1500
            ],
            [
                "id" => "1983.285.a",
                "object" => "Volutenkrater (unteritalisch)",
                "title" => "Fragment eines Volutenkraters (Naiskos-Szene mit zwei Kriegern)",
                "author" => "Gruppe von Kopenhagen 4223 / Trendall, Arthur Dale / Cambitoglou, Alexander",
                "description" => null,
                "material" => "Ton",
                "technique" => "scheibengedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Grab, Grabstätte, Grabdenkmal, stehende Figur, sitzende Figur, junger Mann, Jugendlicher, Waffen, Schwert, Schild (Waffen), Helm, Fächer, Speer, , Palmette (Ornament)",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/fragment-eines-volutenkraters-naiskos-szene-mit-zwei-kriegern/1983.285.a/dc00126687",
                "collection" => "Antike",
                "year_from" => "340 v. Chr.",
                "year_to" => "330 v. Chr.",
                "acquisition_date" => "1917",
                "year" => -340
            ],
            [
                "id" => "1984.530.a",
                "object" => "Oinochoe",
                "title" => "Oinochoe Form VIII B (Hippokamp)",
                "author" => "T.C.-Gruppe / Hurschmann, Rolf / Trendall, Arthur Dale",
                "description" => null,
                "material" => "Ton",
                "technique" => "scheibengedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Fabelwesen, Monster, legendäre Gestalten, Fabeltiere (Huftiere), Palmette (Ornament), Ornamente, Ornamente",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/oinochoe-form-viii-b-hippokamp/1984.530.a/mkg-e00190944",
                "collection" => "Antike",
                "year_from" => "340 v. Chr.",
                "year_to" => "320 v. Chr.",
                "acquisition_date" => "1984",
                "year" => -340
            ],
            [
                "id" => "O1895.155",
                "object" => "Ornamentstich",
                "title" => "Rocaille-Kartusche, Blatt 5 aus der Folge \"Kartuschen\"",
                "author" => "Kilian, Georg Christoph",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Rocaille, Kartusche (Ornament)",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/rocaille-kartusche-blatt-5-aus-der-folge-kartuschen/O1895.155/dc00104811",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730",
                "year_to" => "1750",
                "acquisition_date" => "",
                "year" => 1730
            ],
            [
                "id" => "JB1891.544",
                "object" => "Ornamentstich",
                "title" => "Fries mit Schweifwerkgroteske, Blatt aus der Folge \"Zierhat boichilgen. Zusamen gedragen Durch Johann Halueren Goltschmidgesel\"",
                "author" => "Halver, Johann von",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Groteske (Ornament), Ornamente, Maske (Maskaron), Früchte, Pflanzenornamente, ",
                "style" => "Manierismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/fries-mit-schweifwerkgroteske-blatt-aus-der-folge-zierhat-boichilgen-zusamen-gedragen-durch-johann-h/JB1891.544/dc00101986",
                "collection" => "Grafische Sammlung",
                "year_from" => "1600",
                "year_to" => "1625",
                "acquisition_date" => "1891",
                "year" => 1600
            ],
            [
                "id" => "O1907.219",
                "object" => "Ornamentstich",
                "title" => "Vase auf Sockelaufsatz, dabei Bacchus und Satyrknaben",
                "author" => "Hoppenhaupt der Ältere, Johann Michael / Meil, Johann Wilhelm",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Geschichte des Bacchus (Dionysus), Rocaille, Satyrn, Faune, Silene, Behälter (Stein): Steinvase, Gartenvase, Weintraube, Pflanzenornamente, Kunsthandwerk, Kunstgewerbe, Industriedesign",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/vase-auf-sockelaufsatz-dabei-bacchus-und-satyrknaben/O1907.219/dc00106442",
                "collection" => "Grafische Sammlung",
                "year_from" => "1752 / 1752",
                "year_to" => "1755 / 1755",
                "acquisition_date" => "1907",
                "year" => 1752
            ],
            [
                "id" => "O1907.440",
                "object" => "Ornamentstich",
                "title" => "Medaillon, Putten und zwei Füllungen, Blatt aus der Folge \"Neu inventirtes Formular Büchlein vor Gold und Silber Arbeiter auch andere Künstler sehr dienlich\"",
                "author" => "Biller, Johann Jacob / Rein, Melchior / Jeremias Wolff Erben",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Laub- und Bandelwerk, Amoretten, Putten, Sanduhr, Medaillon (Ornament), Amoretten mit Attributen der Künste, Wissenschaften etc., Früchte, Blumenornamente, Turm, Burg, Schloss",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/medaillon-putten-und-zwei-fullungen-blatt-aus-der-folge-neu-inventirtes-formular-buchlein-vor-gold-u/O1907.440/dc00104029",
                "collection" => "Grafische Sammlung",
                "year_from" => "1723 / 1723",
                "year_to" => "1730 / 1730",
                "acquisition_date" => "1907",
                "year" => 1723
            ],
            [
                "id" => "EG2020.38.39",
                "object" => "Entwurfszeichnung",
                "title" => "Blumenornament. Reinzeichnung für ein Zierstück",
                "author" => "Hahn-Brinckmann, Henriette",
                "description" => null,
                "material" => "Papier, Bleistift, Tusche",
                "technique" => "Pinselzeichnung",
                "iconography" => "Blumenornamente",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/blumenornament-reinzeichnung-fur-ein-zierstuck/EG2020.38.39/mkg-e00191454",
                "collection" => "Grafische Sammlung",
                "year_from" => "1897",
                "year_to" => "1903",
                "acquisition_date" => "",
                "year" => 1897
            ],
            [
                "id" => "O1907.442",
                "object" => "Ornamentstich",
                "title" => "Füllungen, Blatt aus der Folge \"Neu inventirtes Formular Büchlein vor Gold und Silber Arbeiter auch andere Künstler sehr dienlich\"",
                "author" => "Biller, Johann Jacob / Rein, Melchior / Jeremias Wolff Erben",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Laub- und Bandelwerk, Groteske (Ornament), Tiere als Ornament, Tierornamente, Girlanden, Blumengewinde (Ornament), Vögel, Blumen",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/fullungen-blatt-aus-der-folge-neu-inventirtes-formular-buchlein-vor-gold-und-silber-arbeiter-auch-an/O1907.442/dc00104032",
                "collection" => "Grafische Sammlung",
                "year_from" => "1723 / 1723 / 1723",
                "year_to" => "1730 / 1730 / 1730",
                "acquisition_date" => "1907",
                "year" => 1723
            ],
            [
                "id" => "O2014.63",
                "object" => "Ornamentstich",
                "title" => "Kamin, Blatt aus einer Folge",
                "author" => "Hoppenhaupt der Ältere, Johann Michael",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Kamin, Rocaille, Meeresnymphen, Tierornamente, Delphin, Amoretten, Putten, Groteske (Ornament), Kerze, Kunsthandwerk, Kunstgewerbe, Industriedesign",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/kamin-blatt-aus-einer-folge/O2014.63/dc00106439",
                "collection" => "Grafische Sammlung",
                "year_from" => "1740",
                "year_to" => "1750",
                "acquisition_date" => "",
                "year" => 1740
            ],
            [
                "id" => "1886.254",
                "object" => "Bodenstanduhr",
                "title" => "Dielenuhr aus einem Gasthaus in Billwerder",
                "author" => "Emmerich, Johann",
                "description" => null,
                "material" => "Linde, Messing, Zinn",
                "technique" => "geschnitzt, farbig gefasst",
                "iconography" => "Rocaille",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/dielenuhr-aus-einem-gasthaus-in-billwerder/1886.254/dc00021425",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1746",
                "year_to" => "1755",
                "acquisition_date" => "",
                "year" => 1746
            ],
            [
                "id" => "O1913.129",
                "object" => "Ornamentstich",
                "title" => "Fries mit Einzelornamenten, Blatt aus der Folge \"Zierhat boichilgen. Zusamen gedragen Durch Johann Halueren Goltschmidgesel\"",
                "author" => "Halver, Johann von",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Groteske (Ornament), Fabelwesen, Monster, legendäre Gestalten, Vögel, Fabeltiere, Pflanzenornamente",
                "style" => "Manierismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/fries-mit-einzelornamenten-blatt-aus-der-folge-zierhat-boichilgen-zusamen-gedragen-durch-johann-halu/O1913.129/dc00101987",
                "collection" => "Grafische Sammlung",
                "year_from" => "1600",
                "year_to" => "1625",
                "acquisition_date" => "1913",
                "year" => 1600
            ],
            [
                "id" => "1963.23",
                "object" => "Fußschale",
                "title" => "Fußschale (crespina) mit Putto",
                "author" => "Calamelli, Virgiliotto",
                "description" => null,
                "material" => "Majolika, Keramik",
                "technique" => "glasiert, bemalt (Keramik), gebrannt (Keramik)",
                "iconography" => "Amoretten, Putten, Blumen, Rankenornament",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/fussschale-crespina-mit-putto/1963.23/dc00025590",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1556",
                "year_to" => "1575",
                "acquisition_date" => "01.1963",
                "year" => 1556
            ],
            [
                "id" => "O1910.99",
                "object" => "Ornamentstich",
                "title" => "Kanne",
                "author" => "Solis, Virgil",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Ornamente, Amoretten, Putten, Akanthusornament, Arabeske (Ornament), Kanne (Trinkgefäß), Früchte, Pferd, Pflanzenornamente, Behälter, Tiere als Ornament, Kunsthandwerk, Kunstgewerbe, Industriedesign, Tierornamente",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/kanne/O1910.99/dc00101805",
                "collection" => "Grafische Sammlung",
                "year_from" => "1550",
                "year_to" => "1562",
                "acquisition_date" => "1910",
                "year" => 1550
            ],
            [
                "id" => "1882.40",
                "object" => "Vorratstopf",
                "title" => "Apothekenvase mit zwei Profilbildnissen",
                "author" => "Venezia, Domenico da",
                "description" => null,
                "material" => "Majolika, Keramik",
                "technique" => "scheibengedreht, glasiert, bemalt (Keramik), gebrannt (Keramik)",
                "iconography" => "Profil (Seitenansicht), Pflanzenornamente, junge Frau, Mädchen, alter Mann, Brustbild, Dreiviertelansicht",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/apothekenvase-mit-zwei-profilbildnissen/1882.40/dc00020330",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1566",
                "year_to" => "1575",
                "acquisition_date" => "1882",
                "year" => 1566
            ],
            [
                "id" => "O1910.232",
                "object" => "Ornamentstich",
                "title" => "Waffentrophäe mit Adler, Victoria und Historia",
                "author" => "Hopfer, Daniel",
                "description" => null,
                "material" => ", Papier",
                "technique" => "Radierung",
                "iconography" => "Ornamente, Kandelaber (Ornament), Waffen, Schild (Waffen), Adler (Vögel), Victoria, Geschichte, Personifikationen, Rüstung, Panzer",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/waffentrophae-mit-adler-victoria-und-historia/O1910.232/dc00101603",
                "collection" => "Grafische Sammlung",
                "year_from" => "1500",
                "year_to" => "1536",
                "acquisition_date" => "1910",
                "year" => 1500
            ],
            [
                "id" => "O1897.118",
                "object" => "Ornamentstich",
                "title" => "Blumenbeete",
                "author" => "Engelbrecht, Martin / Richter, Siegmund",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich, Radierung",
                "iconography" => "Laub- und Bandelwerk, Gärten und Parks, Blumenbeet, Springbrunnen (Garten), Gartenlabyrinth, Ornamente",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/blumenbeete/O1897.118/dc00103284",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730 / 1730",
                "year_to" => "1750 / 1750",
                "acquisition_date" => "1897",
                "year" => 1730
            ],
            [
                "id" => "1951.32.a-c",
                "object" => "Tasse",
                "title" => "Deckeltasse und Untertasse mit Darstellung der Minerva und Isis",
                "author" => "KPM Königliche Porzellanmanufaktur Berlin",
                "description" => null,
                "material" => "Porzellan",
                "technique" => "gegossen, anbossiert, bemalt (Keramik), glasiert",
                "iconography" => "Geschichte der Minerva (Pallas, Athene), Isis, die Muttergottheit, Profil (Seitenansicht), Helm, Ornamente",
                "style" => "Klassizismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/deckeltasse-und-untertasse-mit-darstellung-der-minerva-und-isis/1951.32.a-c/dc00024725",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1776",
                "year_to" => "1785",
                "acquisition_date" => "28.05.1951",
                "year" => 1776
            ],
            [
                "id" => "2018.13",
                "object" => "Lekythos",
                "title" => "Lekythos (blühender Efeu)",
                "author" => "Beldam-Maler / Hildebrandt, Frank",
                "description" => null,
                "material" => "Ton",
                "technique" => "schnell gedreht, handmodelliert, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Efeu, Weinranke, Weinblatt, Ornamente, Mäander, Pflanzenornamente",
                "style" => "spätarchaisch, , ",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/lekythos-bluhender-efeu/2018.13/mkg-e00161837",
                "collection" => "Antike",
                "year_from" => "500 v. Chr.",
                "year_to" => "480 v. Chr.",
                "acquisition_date" => "19.01.2018",
                "year" => -500
            ],
            [
                "id" => "1885.1100",
                "object" => "Etui, Futteral*",
                "title" => "Pfeifenetui mit Bohnenranken",
                "author" => "Ikeda Taishin 池田泰真",
                "description" => null,
                "material" => "Perlmutt, Gold, Silber, Holz, Lack",
                "technique" => "lackiert, emailliert",
                "iconography" => "Pflanzenornamente",
                "style" => "Edo-Zeit, Meiji-Zeit",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/pfeifenetui-mit-bohnenranken/1885.1100/mkg-e00195106",
                "collection" => "Ostasien",
                "year_from" => "1850 / 1885",
                "year_to" => "1885",
                "acquisition_date" => "1885",
                "year" => 1850
            ],
            [
                "id" => "O1895.507",
                "object" => "Ornamentstich",
                "title" => "Maria mit dem Kinde und Anna in ornamentaler Umrahmung",
                "author" => "Hopfer, Daniel",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Rankenornament, Arabeske (Ornament), Maria mit Christuskind (Madonna), Anna, Nimbus, Heiligenschein (Strahlen von Personen oder ausgehend), thronende Madonna, Säule, Pfeiler (Architektur)",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/maria-mit-dem-kinde-und-anna-in-ornamentaler-umrahmung/O1895.507/dc00101593",
                "collection" => "Grafische Sammlung",
                "year_from" => "1500",
                "year_to" => "1536",
                "acquisition_date" => "1895",
                "year" => 1500
            ],
            [
                "id" => "1875.70",
                "object" => "Teller",
                "title" => "Teller (Frauenkopf)",
                "author" => "T.P.S.-Gruppe / Trendall, Arthur Dale / Cambitoglou, Alexander",
                "description" => null,
                "material" => "Ton",
                "technique" => "scheibengedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Frau, Kopf, Gesicht, Kopfbild, Profil (Seitenansicht), Ornamente",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/teller-frauenkopf/1875.70/dc00123243",
                "collection" => "Antike",
                "year_from" => "330 v. Chr.",
                "year_to" => "300 v. Chr.",
                "acquisition_date" => "1875",
                "year" => -330
            ],
            [
                "id" => "O1911.547",
                "object" => "Ornamentstich",
                "title" => "Säule und zwei Umrahmungen, Blatt 4 aus der Folge \"Gantz Neu sehr nützl. Säulen und andern Ornamenten\"",
                "author" => "Bergmüller, Johann Andreas / Fridrich der Ältere, Jacob Andreas / Jeremias Wolff Erben",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Säule, Pfeiler (Architektur), Kartusche (Ornament), Amoretten, Putten, Akanthusornament, Altar, Laub- und Bandelwerk, Engel (christliche Religion), Ornamente, Verkündigung der Geburt Christi, Erzengel Gabriel, Maria, Rüstung, Panzer",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/saule-und-zwei-umrahmungen-blatt-4-aus-der-folge-gantz-neu-sehr-nutzl-saulen-und-andern-ornamenten/O1911.547/dc00106303",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730 / 1730 / 1730",
                "year_to" => "1738 / 1740 / 1740",
                "acquisition_date" => "",
                "year" => 1730
            ],
            [
                "id" => "O1910.101",
                "object" => "Ornamentstich",
                "title" => "Adam, Blatt aus der Folge Gottvater, Adam und Eva mit reicher Rahmung",
                "author" => "Solis, Virgil",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Ornamente, Vögel, Maske (Maskaron), Behälter, Satyrn, Faune, Silene, Adam, Tiere als Ornament",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/adam-blatt-aus-der-folge-gottvater-adam-und-eva-mit-reicher-rahmung/O1910.101/dc00101779",
                "collection" => "Grafische Sammlung",
                "year_from" => "1550",
                "year_to" => "1562",
                "acquisition_date" => "1910",
                "year" => 1550
            ],
            [
                "id" => "2002.257",
                "object" => "Vase",
                "title" => "",
                "author" => "Massier, Jean Baptiste",
                "description" => null,
                "material" => "Steinzeug",
                "technique" => "glasiert",
                "iconography" => "Laub- und Bandelwerk",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/vase/2002.257/dc00006364",
                "collection" => "Kunstgewerbe und Design",
                "year_from" => "1896",
                "year_to" => "1905",
                "acquisition_date" => "2002",
                "year" => 1896
            ],
            [
                "id" => "1900.434",
                "object" => "Steckkamm",
                "title" => "Schmuckkamm \"Schneeglöckchen\"",
                "author" => "Vever Frères",
                "description" => null,
                "material" => "Schildpatt, Gold, Metall",
                "technique" => "emailliert, bemalt",
                "iconography" => "Blumen, Blumenornamente, ",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/schmuckkamm-schneeglockchen/1900.434/dc00001099",
                "collection" => "Kunstgewerbe und Design",
                "year_from" => "1899",
                "year_to" => "1900",
                "acquisition_date" => "1900",
                "year" => 1899
            ],
            [
                "id" => "1882.211",
                "object" => "Teller",
                "title" => "Teller (piatto) mit Judith mit dem Haupt des Holofernes",
                "author" => "Grue, Carlo Antonio / Rubens, Peter Paul / Voet, Alexander",
                "description" => null,
                "material" => "Majolika, Keramik",
                "technique" => "scheibengedreht, bemalt (Keramik), Unterglasurdekor, Aufglasurdekor, glasiert, gebrannt (Keramik)",
                "iconography" => "Judith und Holofernes, Amoretten, Putten, Akanthusornament, Maske (Maskaron)",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/teller-piatto-mit-judith-mit-dem-haupt-des-holofernes/1882.211/dc00020356",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1696",
                "year_to" => "1705",
                "acquisition_date" => "1882",
                "year" => 1696
            ],
            [
                "id" => "1917.812.a-b",
                "object" => "Lekanis",
                "title" => "Lekanis mit Deckel (A: Frauenkopf | B: Vogel)",
                "author" => "Parrish-Maler / Hurschmann, Rolf",
                "description" => null,
                "material" => "Ton",
                "technique" => "scheibengedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Frau, Profil (Seitenansicht), Kopfbild, Kopf, Gesicht, Vögel, Palmette (Ornament), Rankenornament",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/lekanis-mit-deckel-a-frauenkopf-b-vogel/1917.812.a-b/dc00124392",
                "collection" => "Antike",
                "year_from" => "366 v. Chr.",
                "year_to" => "334 v. Chr.",
                "acquisition_date" => "",
                "year" => -366
            ],
            [
                "id" => "O1913.131",
                "object" => "Ornamentstich",
                "title" => "Fries mit Einzelornamenten, Blatt aus der Folge \"Zierhat boichilgen. Zusamen gedragen Durch Johann Halueren Goltschmidgesel\"",
                "author" => "Halver, Johann von",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Groteske (Ornament), Palmette (Ornament), Ornamente, Eierstab, Edel- und Halbedelsteine, Tierornamente",
                "style" => "Manierismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/fries-mit-einzelornamenten-blatt-aus-der-folge-zierhat-boichilgen-zusamen-gedragen-durch-johann-halu/O1913.131/dc00101990",
                "collection" => "Grafische Sammlung",
                "year_from" => "1600",
                "year_to" => "1625",
                "acquisition_date" => "1913",
                "year" => 1600
            ],
            [
                "id" => "1984.492.a-b",
                "object" => "Halsamphora",
                "title" => "Halsamphora mit Deckel (A: Viergespann | B: Zweikampf über einem Gefallenen)",
                "author" => "Maler der Halsamphora Oxford 213 / Moore, M. B.",
                "description" => null,
                "material" => "Ton",
                "technique" => "schnell gedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Kampf (Duell), mit Tieren bespannte Fahrzeuge (Kutsche etc.), Besiegte, Krieg, Streitwagen, Ornamente",
                "style" => "spätarchaisch, Griechische Antike, ",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/halsamphora-mit-deckel-a-viergespann-b-zweikampf-uber-einem-gefallenen/1984.492.a-b/dc00126754",
                "collection" => "Antike",
                "year_from" => "520 v. Chr.",
                "year_to" => "510 v. Chr.",
                "acquisition_date" => "1984",
                "year" => -520
            ],
            [
                "id" => "O1895.157",
                "object" => "Ornamentstich",
                "title" => "Rocaille-Kartusche, Blatt 7 aus der Folge \"Kartuschen\"",
                "author" => "Kilian, Georg Christoph",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Rocaille, Kartusche (Ornament)",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/rocaille-kartusche-blatt-7-aus-der-folge-kartuschen/O1895.157/dc00104813",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730",
                "year_to" => "1750",
                "acquisition_date" => "",
                "year" => 1730
            ],
            [
                "id" => "1906.552",
                "object" => "Terrine",
                "title" => "Soupière mit den Bildnissen von Lotte und Werther sowie Lord Adelson und Salvini",
                "author" => "Königlich Sächsische Porzellan-Manufaktur (Meißen)",
                "description" => null,
                "material" => "Porzellan",
                "technique" => "bemalt (Keramik), vergoldet",
                "iconography" => "Liebende, Liebespaar, Porträt, Lit. Charaktere, Medaillon (Ornament)",
                "style" => "Klassizismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/soupiere-mit-den-bildnissen-von-lotte-und-werther-sowie-lord-adelson-und-salvini/1906.552/mkg-e00110492",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1775",
                "year_to" => "1820",
                "acquisition_date" => "1906",
                "year" => 1775
            ],
            [
                "id" => "BZV1928.215",
                "object" => "Buch",
                "title" => "Johann Arndt: Postilla, im Metall-Einband",
                "author" => "Arndt, Johann / Druckerei und Verlag der Sterne Lüneburg",
                "description" => null,
                "material" => "Papier, Kupfer",
                "technique" => "Buchdruck, Kupferstich",
                "iconography" => "Gottvater, Glaube (Fides), Liebe, Nächstenliebe (Charitas), Hoffnung (Spes), Herzsymbolik, Tiere als Symbole, Ornamente",
                "style" => "Spätbarock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/johann-arndt-postilla-im-metall-einband/BZV1928.215/mkg-e00196585",
                "collection" => "Buchkunst",
                "year_from" => "1712",
                "year_to" => "1712",
                "acquisition_date" => "23.08.1928",
                "year" => 1712
            ],
            [
                "id" => "BZV2022.1112",
                "object" => "Bucheinband",
                "title" => "Ornamentierter Ledereinband im orientalischen Stil",
                "author" => "Jebsen, Gustav",
                "description" => null,
                "material" => "Ziegenleder",
                "technique" => "vergoldet, ",
                "iconography" => "Ornamente",
                "style" => "Historismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/ornamentierter-ledereinband-im-orientalischen-stil/BZV2022.1112/dc00000185",
                "collection" => "Buchkunst",
                "year_from" => "1880",
                "year_to" => "1885",
                "acquisition_date" => "",
                "year" => 1880
            ],
            [
                "id" => "EP1989.113",
                "object" => "Plakat",
                "title" => "La Réforme - Le masque Anarchiste, Montjuich",
                "author" => "Privat-Livemont, Henri / Trommer & Staeves",
                "description" => null,
                "material" => "Papier",
                "technique" => "Lithografie",
                "iconography" => "Tod durch Unfall, Mord, Selbstmord, Frau, Mann, Axt, Beil, kniende Figur, liegende Figur, Kopfbedeckung, Wald, Schwert, Schädel, Blumenornamente, Narbe, Wundmal, Blut",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/la-reforme-le-masque-anarchiste-montjuich/EP1989.113/dc00067726",
                "collection" => "Plakatsammlung",
                "year_from" => "1897 / 1897",
                "year_to" => "1899",
                "acquisition_date" => "",
                "year" => 1897
            ],
            [
                "id" => "BZV2018.353",
                "object" => "Buch",
                "title" => "Hypnerotomachie, ou Discours du songe de Poliphile",
                "author" => "Kerver, Jacques / Martin, Jean / Unbekannt / Colonna, Francesco",
                "description" => null,
                "material" => "Papier, Leder",
                "technique" => "Buchdruck, Holzschnitt",
                "iconography" => "Ornamente, Lit. Charaktere, Traum",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/hypnerotomachie-ou-discours-du-songe-de-poliphile/BZV2018.353/mkg-e00162806",
                "collection" => "Buchkunst",
                "year_from" => "1561 / 2018 / 1450",
                "year_to" => "1499",
                "acquisition_date" => "23.02.2018",
                "year" => 1561
            ],
            [
                "id" => "1981.173",
                "object" => "Oinochoe (Attischer Typus 7)",
                "title" => "Oinochoe ('Eurymedon-Kanne' oder 'Perser-Kanne')",
                "author" => "Triptolemos-Maler / Schauenburg, Konrad",
                "description" => null,
                "material" => "Ton",
                "technique" => "schnell gedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Völker und Nationalitäten, Völker und Nationalitäten, Theater, Theateraufführung, Mäander",
                "style" => "Strenger Stil, , ",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/oinochoe-eurymedon-kanne-oder-perser-kanne/1981.173/dc00126657",
                "collection" => "Antike",
                "year_from" => "475 v. Chr.",
                "year_to" => "451 v. Chr.",
                "acquisition_date" => "1981",
                "year" => -475
            ],
            [
                "id" => "1962.124",
                "object" => "Oinochoe (Attischer Typus 3)",
                "title" => "Choen-Kanne - Oinochoe Form III (Bauer mit Esel)",
                "author" => "Niobiden-Maler / Beazley, John D.",
                "description" => null,
                "material" => "Ton",
                "technique" => "schnell gedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Mann, Esel, Mäander, Palmette (Ornament), Bauern, Landwirtschaft, landwirtschaftliche Arbeitsgeräte",
                "style" => "Strenger Stil, Griechische Antike, ",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/choen-kanne-oinochoe-form-iii-bauer-mit-esel/1962.124/dc00126054",
                "collection" => "Antike",
                "year_from" => "460 v. Chr.",
                "year_to" => " v. Chr.",
                "acquisition_date" => "03.05.1962",
                "year" => -460
            ],
            [
                "id" => "1875.37",
                "object" => "Amphora",
                "title" => "Amphora (A | B: Frauenkopf)",
                "author" => "Amphora-Maler / Trendall, Arthur Dale / Cambitoglou, Alexander",
                "description" => null,
                "material" => "Ton",
                "technique" => "schnell gedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Profil (Seitenansicht), Palmette (Ornament), Ornamente, Schmuck, Juwelen, Frisur, Frau, Kopf, Gesicht",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/amphora-a-b-frauenkopf/1875.37/dc00123218",
                "collection" => "Antike",
                "year_from" => "340 v. Chr.",
                "year_to" => "330 v. Chr.",
                "acquisition_date" => "1875",
                "year" => -340
            ],
            [
                "id" => "1957.65",
                "object" => "Kanne (Gefäß)",
                "title" => "Kanne mit Szenerie aus Früchten, Blumen und zwei Vögeln",
                "author" => "Pescetto Werkstatt",
                "description" => null,
                "material" => "Majolika, Keramik",
                "technique" => "glasiert, bemalt (Keramik), gebrannt (Keramik)",
                "iconography" => "Vögel, Pflanzenornamente",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/kanne-mit-szenerie-aus-fruchten-blumen-und-zwei-vogeln/1957.65/dc00019121",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1625",
                "year_to" => "1675",
                "acquisition_date" => "01.07.1957",
                "year" => 1625
            ],
            [
                "id" => "1874.80.a-b",
                "object" => "Lebes Gamikos",
                "title" => "Lebes Gamikos (A | B: Frauenkopf)",
                "author" => "Meo-Evoli-Maler / Trendall, Arthur Dale / Cambitoglou, Alexander",
                "description" => null,
                "material" => "Ton",
                "technique" => "scheibengedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Profil (Seitenansicht), Palmette (Ornament), Ornamente, Schmuck, Juwelen, Frisur, Frau, Kopf, Gesicht",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/lebes-gamikos-a-b-frauenkopf/1874.80.a-b/dc00123211",
                "collection" => "Antike",
                "year_from" => "325 v. Chr.",
                "year_to" => "301 v. Chr.",
                "acquisition_date" => "1874",
                "year" => -325
            ],
            [
                "id" => "O1910.235",
                "object" => "Ornamentstich",
                "title" => "Zwölf Paar ornamentierte Schild- und Gefäßhalter",
                "author" => "Hopfer, Daniel",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Groteske (Ornament), Rankenornament, Amoretten, Putten, Tiere als Ornament, Fabeltiere, Fabelwesen, Monster, legendäre Gestalten, Kunsthandwerk, Kunstgewerbe, Industriedesign, Tierornamente",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/zwolf-paar-ornamentierte-schild-und-gefasshalter/O1910.235/dc00101601",
                "collection" => "Grafische Sammlung",
                "year_from" => "1500",
                "year_to" => "1536",
                "acquisition_date" => "1910",
                "year" => 1500
            ],
            [
                "id" => "1904.224",
                "object" => "Kaffeekanne",
                "title" => "Kaffeekanne",
                "author" => "Josiah Wedgwood & Sons",
                "description" => null,
                "material" => "Steinzeug",
                "technique" => "gegossen, geklebt, gebrannt (Keramik)",
                "iconography" => "Akanthusornament, Frau, Taube",
                "style" => "Klassizismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/kaffeekanne/1904.224/dc00023567",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1781",
                "year_to" => "1790",
                "acquisition_date" => "",
                "year" => 1781
            ],
            [
                "id" => "1984.448",
                "object" => "Patera",
                "title" => "Patera Form II 4 - Knopfhenkelschale (A | B: Frauen mit jungem Mann | Innen: Brautwerbung mit Eros)",
                "author" => "Unterwelt-Maler / Trendall, Arthur Dale / Cambitoglou, Alexander",
                "description" => null,
                "material" => "Ton",
                "technique" => "scheibengedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Verlobung und Hochzeit, Diener, Begleiter, Gefährten, Grabdenkmal, stehende Figur, Frau, junger Mann, Jugendlicher, Katze, Vögel, Palmette (Ornament), Eierstab, Mäander, Bäume, Sträucher, Rankenornament, Weinranke, Weinblatt, Efeu, Spiegel, Schmuckkasten,...",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/patera-form-ii-4-knopfhenkelschale-a-b-frauen-mit-jungem-mann-innen-brautwerbung-mit-eros/1984.448/dc00126709",
                "collection" => "Antike",
                "year_from" => "330 v. Chr.",
                "year_to" => "320 v. Chr.",
                "acquisition_date" => "1984",
                "year" => -330
            ],
            [
                "id" => "EP2009.806",
                "object" => "Plakat",
                "title" => "Secession. 16. Ausstellung d. Vereinigung bildender Künstler Österreichs",
                "author" => "Roller, Alfred / Lithographische Anstalt Albert Berger / Ver Sacrum / Wiener Secession",
                "description" => null,
                "material" => "Papier",
                "technique" => "Lithografie",
                "iconography" => "Kunstausstellung, Gesellschaft, Organisation, Buchstaben, Alphabet, Schrift, Ornamente",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/secession-16-ausstellung-d-vereinigung-bildender-kunstler-osterreichs/EP2009.806/dc00056652",
                "collection" => "Plakatsammlung",
                "year_from" => "1902 / 1902 / 1903 / 1903",
                "year_to" => "1903",
                "acquisition_date" => "",
                "year" => 1902
            ],
            [
                "id" => "JB1891.543",
                "object" => "Ornamentstich",
                "title" => "Fries mit Einzelornamenten, Blatt aus der Folge \"Zierhat boichilgen. Zusamen gedragen Durch Johann Halueren Goltschmidgesel\"",
                "author" => "Halver, Johann von",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Groteske (Ornament), Maske (Maskaron), Tierornamente, Haltungen, Stellungen der menschlichen Figur, Vögel",
                "style" => "Manierismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/fries-mit-einzelornamenten-blatt-aus-der-folge-zierhat-boichilgen-zusamen-gedragen-durch-johann-halu/JB1891.543/dc00101985",
                "collection" => "Grafische Sammlung",
                "year_from" => "1600",
                "year_to" => "1625",
                "acquisition_date" => "1891",
                "year" => 1600
            ],
            [
                "id" => "2018.206",
                "object" => "Vase",
                "title" => "Eisenvase mit Faunsmaskarons",
                "author" => "Schinkel, Karl Friedrich / Kunstgießerei Gleiwitz",
                "description" => null,
                "material" => "Eisen",
                "technique" => "gegossen, gedreht, geschweißt, geschraubt",
                "iconography" => "Maske (Maskaron)",
                "style" => "Klassizismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/eisenvase-mit-faunsmaskarons/2018.206/mkg-e00172513",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1800 / 1800",
                "year_to" => "1804 / 1804",
                "acquisition_date" => "2018",
                "year" => 1800
            ],
            [
                "id" => "O1973.6.34",
                "object" => "Ornamentstich",
                "title" => "Der Hochedle Herr Kiakouli im Lusthaus",
                "author" => "Engelbrecht, Martin / Engelbrecht, Martin",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Hof, Innenhof, Volkstracht, regionale Tracht, Völker und Nationalitäten, Affen, Vögel, Ornamente, Palme",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/der-hochedle-herr-kiakouli-im-lusthaus/O1973.6.34/dc00103073",
                "collection" => "Grafische Sammlung",
                "year_from" => "1740 / 1740",
                "year_to" => "1756 / 1756",
                "acquisition_date" => "1922",
                "year" => 1740
            ],
            [
                "id" => "O2013.12",
                "object" => "Ornamentstich",
                "title" => "Aufsteigende Kandelabergroteske",
                "author" => "Hopfer, Lambert",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Groteske (Ornament), Fabelwesen, Monster, legendäre Gestalten, Akanthusornament, Kandelaber (Ornament), Amoretten, Putten",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/aufsteigende-kandelabergroteske/O2013.12/dc00101652",
                "collection" => "Grafische Sammlung",
                "year_from" => "1500",
                "year_to" => "1540",
                "acquisition_date" => "1918",
                "year" => 1500
            ],
            [
                "id" => "EP2010.206",
                "object" => "Plakat",
                "title" => "La Colonia Libera - Musica di P. Floridia",
                "author" => "Metlicovitz, Leopoldo / G. Ricordi & C.",
                "description" => null,
                "material" => "Papier",
                "technique" => "Lithografie",
                "iconography" => "Pflanzenornamente, Frisurenmode, Haarmode, Brustbild, Dreiviertelansicht, Frau, Weiblichkeit, Orchidee, Musik, Opernsängerin",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/la-colonia-libera-musica-di-p-floridia/EP2010.206/dc00056922",
                "collection" => "Plakatsammlung",
                "year_from" => "1899 / 1899",
                "year_to" => "1900 / 1900",
                "acquisition_date" => "",
                "year" => 1899
            ],
            [
                "id" => "1876.207.a-b",
                "object" => "Tasse",
                "title" => "Tasse mit Abbildung trinkender Tauben",
                "author" => "Kaiserlich-Königliche Wiener Porzellanmanufaktur",
                "description" => null,
                "material" => "Porzellan",
                "technique" => "gegossen, bemalt (Keramik), glasiert",
                "iconography" => "Taube, Ornamente, Essservice, Essgeschirr",
                "style" => "Klassizismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/tasse-mit-abbildung-trinkender-tauben/1876.207.a-b/dc00019438",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1801",
                "year_to" => "1802",
                "acquisition_date" => "",
                "year" => 1801
            ],
            [
                "id" => "1879.71",
                "object" => "Sekretär",
                "title" => "Pultschreibschrank",
                "author" => "Fiedler, Johann Gottlob",
                "description" => null,
                "material" => "Eiche, Eibe, Holz, Laubholz, Rosenholz, Buchsbaum, Birke, Nussbaum, Mahagoni, Ahorn, Ebenholz",
                "technique" => "Marketerie",
                "iconography" => "Ruinen, Porträt, Medaillon (Ornament), Girlanden, Blumengewinde (Ornament)",
                "style" => "Klassizismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/pultschreibschrank/1879.71/dc00019940",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1769",
                "year_to" => "1775",
                "acquisition_date" => "1879",
                "year" => 1769
            ],
            [
                "id" => "1905.746",
                "object" => "Vase",
                "title" => "Langhalsvase",
                "author" => "Elmqvist, Hugo C. M.",
                "description" => null,
                "material" => "Bronze",
                "technique" => "gegossen, reliefiert, patiniert",
                "iconography" => "Efeu, Pflanzenornamente, Käfer",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/langhalsvase/1905.746/dc00001206",
                "collection" => "Kunstgewerbe und Design",
                "year_from" => "1899",
                "year_to" => "1909",
                "acquisition_date" => "1905",
                "year" => 1899
            ],
            [
                "id" => "O2014.60",
                "object" => "Ornamentstich",
                "title" => "Wandtisch, Blatt aus einer Folge",
                "author" => "Hoppenhaupt der Ältere, Johann Michael",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Tisch, Rocaille, junger Mann, Jugendlicher, junge Frau, Mädchen, Beziehungen zwischen den Geschlechtern, Saiteninstrumente (Zupfinstrumente), Musizieren, Pflanzenornamente, Girlanden, Blumengewinde (Ornament), Tierornamente, Vögel, Kunsthandwerk, Kunstgew...",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/wandtisch-blatt-aus-einer-folge/O2014.60/dc00106427",
                "collection" => "Grafische Sammlung",
                "year_from" => "1740",
                "year_to" => "1750",
                "acquisition_date" => "",
                "year" => 1740
            ],
            [
                "id" => "1878.707",
                "object" => "Albarello",
                "title" => "Großes Apothekengefäß (Albarello)",
                "author" => "Venezia, Domenico da",
                "description" => null,
                "material" => "Majolika, Keramik",
                "technique" => "bemalt (Keramik), glasiert, gebrannt (Keramik)",
                "iconography" => "Halbprofil (Dreiviertelansicht), Rankenornament, Frau, Ornamente, Buchstaben, Alphabet, Schrift, Amoretten, Putten",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/grosses-apothekengefass-albarello/1878.707/dc00019151",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1566",
                "year_to" => "1575",
                "acquisition_date" => "1878",
                "year" => 1566
            ],
            [
                "id" => "1884.225.a-b",
                "object" => "Tasse",
                "title" => "Tasse mit Fries aus spielenden Putten",
                "author" => "Josiah Wedgwood & Sons",
                "description" => null,
                "material" => "Steingut",
                "technique" => "gegossen, geklebt, gebrannt (Keramik)",
                "iconography" => "Amoretten, Putten, Hund, Bäume, Sträucher, Insekten, Vögel, Pflanzenornamente",
                "style" => "Klassizismus",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/tasse-mit-fries-aus-spielenden-putten/1884.225.a-b/dc00020573",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1781",
                "year_to" => "1790",
                "acquisition_date" => "1884",
                "year" => 1781
            ],
            [
                "id" => "EP2022.159",
                "object" => "Plakat",
                "title" => "Weinrestaurant zum Kunstgewerbehaus beim Promenadeplatz - Hofweinhandlung J. Eberspacher",
                "author" => "La Roche, Maria / Klein & Volbert",
                "description" => null,
                "material" => "Papier",
                "technique" => "Lithografie",
                "iconography" => "Weinranke, Weinblatt, Weintraube, Pflanzenornamente",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/weinrestaurant-zum-kunstgewerbehaus-beim-promenadeplatz-hofweinhandlung-j-eberspacher/EP2022.159/mkg-e00214812",
                "collection" => "Plakatsammlung",
                "year_from" => "1895 / 1895",
                "year_to" => "1905 / 1905",
                "acquisition_date" => "",
                "year" => 1895
            ],
            [
                "id" => "O1907.438",
                "object" => "Ornamentstich",
                "title" => "Pokal, Blatt aus der Folge \"Neu inventirtes Formular Büchlein vor Gold und Silber Arbeiter auch andere Künstler sehr dienlich\"",
                "author" => "Biller, Johann Jacob / Rein, Melchior / Jeremias Wolff Erben",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Laub- und Bandelwerk, Groteske (Ornament), Maske (Maskaron), Krug, Becher, Pokal, Girlanden, Blumengewinde (Ornament), Amoretten, Putten, Kunsthandwerk, Kunstgewerbe, Industriedesign",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/pokal-blatt-aus-der-folge-neu-inventirtes-formular-buchlein-vor-gold-und-silber-arbeiter-auch-andere/O1907.438/dc00104008",
                "collection" => "Grafische Sammlung",
                "year_from" => "1723 / 1723 / 1723",
                "year_to" => "1730 / 1730 / 1730",
                "acquisition_date" => "1907",
                "year" => 1723
            ],
            [
                "id" => "1991.215",
                "object" => "Standarte",
                "title" => "Standartenbekrönung mit Koransure für religiöse Prozessionen",
                "author" => "Meister Hasan / Motamed, Saeed ",
                "description" => null,
                "material" => "Stahl, Kupfer, Messing, Eisen",
                "technique" => "Durchbruch, gegossen",
                "iconography" => "arabische Schrift, Blumenornamente, Licht",
                "style" => "Safawiden",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/standartenbekronung-mit-koransure-fur-religiose-prozessionen/1991.215/dc00119150",
                "collection" => "Islamische Kunst",
                "year_from" => "1700 / 1700 / 1991",
                "year_to" => "1701 / 1701",
                "acquisition_date" => "1991",
                "year" => 1700
            ],
            [
                "id" => "EP2009.789",
                "object" => "Plakat",
                "title" => "Böcklin. Hagenbund",
                "author" => "Keller, Alfred / Christoph Reisser's Söhne / Künstlerbund Hagen",
                "description" => null,
                "material" => ", Papier",
                "technique" => "Lithografie",
                "iconography" => "Pflanzenornamente, Kranz, Girlande, Ornamente",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/bocklin-hagenbund/EP2009.789/dc00056635",
                "collection" => "Plakatsammlung",
                "year_from" => "1902 / 1902 / 1902",
                "year_to" => "1903 / 1903 / 1903",
                "acquisition_date" => "",
                "year" => 1902
            ],
            [
                "id" => "1966.89",
                "object" => "Halsamphora",
                "title" => "Halsamphora (Hals: Totenaufbahrung | Körper: Streitwagen und Krieger)",
                "author" => "Werkstatt von Athen 894",
                "description" => null,
                "material" => "Ton",
                "technique" => "schnell gedreht, handmodelliert, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Begräbnis, Streitwagen, sterben (Totenbett), Mäander",
                "style" => "spätgeometrisch, ",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/halsamphora-hals-totenaufbahrung-korper-streitwagen-und-krieger/1966.89/dc00126278",
                "collection" => "Antike",
                "year_from" => "725 v. Chr.",
                "year_to" => "710 v. Chr.",
                "acquisition_date" => "20.07.1966",
                "year" => -725
            ],
            [
                "id" => "1984.447.b",
                "object" => "Hydria",
                "title" => "Hydria (Naiskos-Szene)",
                "author" => "Varrese-Maler / Gioia del Colle-Maler / Trendall, Arthur Dale / Cambitoglou, Alexander / Hurschmann, Rolf",
                "description" => null,
                "material" => "Ton",
                "technique" => "schnell gedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Architektur, Grab, Grabstätte, Mäander, Pflanzenornamente, Frau, Leichnam, Fächer, männlicher Akt, Eierstab",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/hydria-naiskos-szene/1984.447.b/dc00126708",
                "collection" => "Antike",
                "year_from" => "340 v. Chr.",
                "year_to" => "330 v. Chr.",
                "acquisition_date" => "1984",
                "year" => -340
            ],
            [
                "id" => "1900.245",
                "object" => "Kumme (Schale)",
                "title" => "Becher mit Silberfassung",
                "author" => "Dalpayrat, Pierre Adrien / Bing, Marcel",
                "description" => null,
                "material" => "Steinzeug, Silber",
                "technique" => "glasiert, montiert, geschliffen",
                "iconography" => "Pflanzenornamente",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/becher-mit-silberfassung/1900.245/dc00000977",
                "collection" => "Kunstgewerbe und Design",
                "year_from" => "1896 / 1896",
                "year_to" => "1900 / 1900",
                "acquisition_date" => "1900",
                "year" => 1896
            ],
            [
                "id" => "O1895.518",
                "object" => "Ornamentstich",
                "title" => "Kanne",
                "author" => "Solis, Virgil",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Ornamente, Maske (Maskaron), Kanne (Trinkgefäß), Schlangen, Behälter, Schildkröten, Tiere als Ornament, Kunsthandwerk, Kunstgewerbe, Industriedesign, Tierornamente, Eidechsen",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/kanne/O1895.518/dc00101806",
                "collection" => "Grafische Sammlung",
                "year_from" => "1550",
                "year_to" => "1562",
                "acquisition_date" => "",
                "year" => 1550
            ],
            [
                "id" => "P1976.105.18",
                "object" => "Fotografie",
                "title" => "Architekturstudie",
                "author" => "Angenendt, Erich",
                "description" => null,
                "material" => "Silbergelatinepapier",
                "technique" => "Schwarzweißpositivverfahren",
                "iconography" => "Architektur, architektonische Details, Fassade (Haus/Gebäude), Fassadendekorationen (Architektur), Fenster, Ornamente",
                "style" => "Subjektive Fotografie",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/architekturstudie/P1976.105.18/dc00040752",
                "collection" => "Fotografie und neue Medien",
                "year_from" => "1948",
                "year_to" => "1956",
                "acquisition_date" => "1976",
                "year" => 1948
            ],
            [
                "id" => "1917.1075.b",
                "object" => "Deckel (Gefäß)",
                "title" => "Deckel einer Lekanis (A: Eros | B: sitzende Frau an Grabpfeiler)",
                "author" => "Maler des Knienden Eros / Trendall, Arthur Dale",
                "description" => null,
                "material" => "Ton",
                "technique" => "scheibengedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Diener, Begleiter, Gefährten, Geschichte des Cupido, Amor (Eros), Frau, sitzende Figur, Grabdenkmal, Palmette (Ornament), Rankenornament, kniende Figur",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/deckel-einer-lekanis-a-eros-b-sitzende-frau-an-grabpfeiler/1917.1075.b/dc00124627",
                "collection" => "Antike",
                "year_from" => "380 v. Chr.",
                "year_to" => "360 v. Chr.",
                "acquisition_date" => "1917",
                "year" => -380
            ],
            [
                "id" => "O1895.154",
                "object" => "Ornamentstich",
                "title" => "Rocaille-Kartusche, Blatt 4 aus der Folge \"Kartuschen\"",
                "author" => "Kilian, Georg Christoph",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Rocaille, Kartusche (Ornament)",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/rocaille-kartusche-blatt-4-aus-der-folge-kartuschen/O1895.154/dc00104810",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730",
                "year_to" => "1750",
                "acquisition_date" => "",
                "year" => 1730
            ],
            [
                "id" => "O1896.175",
                "object" => "Ornamentstich",
                "title" => "Eine Kartusche mit Muschelwerk und figürlicher Szene, Titelblatt der Folge \"Cartouches Modernes orné avec des diferentes Figures\"",
                "author" => "Nilson, Johann Esaias / Balzer, Johann Heinrich / Balzer, Johann Heinrich",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Rocaille, Kartusche (Ornament), Ornamente, Haltungen, Stellungen der menschlichen Figur, Pflanzenornamente, Loggia, Veranda",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/eine-kartusche-mit-muschelwerk-und-figurlicher-szene-titelblatt-der-folge-cartouches-modernes-orne-a/O1896.175/dc00104884",
                "collection" => "Grafische Sammlung",
                "year_from" => "1750 / 1765",
                "year_to" => "1760 / 1799",
                "acquisition_date" => "1896",
                "year" => 1750
            ],
            [
                "id" => "O1895.158",
                "object" => "Ornamentstich",
                "title" => "Rocaille-Kartusche, Blatt 8 aus der Folge \"Kartuschen\"",
                "author" => "Kilian, Georg Christoph",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Rocaille, Kartusche (Ornament)",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/rocaille-kartusche-blatt-8-aus-der-folge-kartuschen/O1895.158/dc00104814",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730",
                "year_to" => "1750",
                "acquisition_date" => "",
                "year" => 1730
            ],
            [
                "id" => "O1910.100",
                "object" => "Ornamentstich",
                "title" => "Salvator, Blatt aus der Folge Gottvater, Adam und Eva mit reicher Rahmung",
                "author" => "Solis, Virgil",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Ornamente, Maske (Maskaron), Christus, Salvator Mundi, Kreuz, Tiere als Ornament, weiblicher Akt, Blumen",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/salvator-blatt-aus-der-folge-gottvater-adam-und-eva-mit-reicher-rahmung/O1910.100/dc00101766",
                "collection" => "Grafische Sammlung",
                "year_from" => "1550",
                "year_to" => "1562",
                "acquisition_date" => "1910",
                "year" => 1550
            ],
            [
                "id" => "O2014.65",
                "object" => "Ornamentstich",
                "title" => "Sofa, Blatt aus einer Folge",
                "author" => "Hoppenhaupt der Ältere, Johann Michael",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Couch, Sofa, Kanapee, Rocaille, Möbel und Hausrat, Kunsthandwerk, Kunstgewerbe, Industriedesign, Tierornamente, Vögel, Girlanden, Blumengewinde (Ornament)",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/sofa-blatt-aus-einer-folge/O2014.65/dc00106449",
                "collection" => "Grafische Sammlung",
                "year_from" => "1740",
                "year_to" => "1752",
                "acquisition_date" => "",
                "year" => 1740
            ],
            [
                "id" => "O1897.114",
                "object" => "Ornamentstich",
                "title" => "Blumenbeete",
                "author" => "Engelbrecht, Martin / Richter, Siegmund",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich, Radierung",
                "iconography" => "Gärten und Parks, Blumenbeet, Springbrunnen (Garten), Gartenlabyrinth, Ornamente, Entwurf, Plan eines Gebäudes",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/blumenbeete/O1897.114/dc00103280",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730 / 1730",
                "year_to" => "1750 / 1750",
                "acquisition_date" => "1897",
                "year" => 1730
            ],
            [
                "id" => "O1907.763",
                "object" => "Ornamentstich",
                "title" => "Dolchscheide",
                "author" => "Pencz, Georg",
                "description" => null,
                "material" => "Papier",
                "technique" => "Kupferstich",
                "iconography" => "Groteske (Ornament), Kandelaber (Ornament), weiblicher Akt, Tierornamente",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/dolchscheide/O1907.763/dc00101659",
                "collection" => "Grafische Sammlung",
                "year_from" => "1530",
                "year_to" => "1550",
                "acquisition_date" => "1907",
                "year" => 1530
            ],
            [
                "id" => "EP2009.272",
                "object" => "Plakat",
                "title" => "Salón pedal. Carreras diarias",
                "author" => "Riquer, Alexandre de",
                "description" => null,
                "material" => "Papier",
                "technique" => "Lithografie",
                "iconography" => "Fahrrad, Zweirad, Frau, Hut, Blumen, Pflanzenornamente",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/salon-pedal-carreras-diarias/EP2009.272/dc00056035",
                "collection" => "Plakatsammlung",
                "year_from" => "1898",
                "year_to" => "1900",
                "acquisition_date" => "",
                "year" => 1898
            ],
            [
                "id" => "1988.7.b",
                "object" => "Kantharos",
                "title" => "Kantharos Sessile (St. Valentins-Klasse)",
                "author" => "St. Valentins-Klasse / Hurschmann, Rolf / Ewigleben, Cornelia",
                "description" => null,
                "material" => "Ton",
                "technique" => "scheibengedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Ornamente, Kranz, Girlande",
                "style" => "Hochklassik  (Griechische Antike), Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/kantharos-sessile-st-valentins-klasse/1988.7.b/dc00126836",
                "collection" => "Antike",
                "year_from" => "480 v. Chr.",
                "year_to" => "301 v. Chr.",
                "acquisition_date" => "",
                "year" => -480
            ],
            [
                "id" => "O2014.64",
                "object" => "Ornamentstich",
                "title" => "Kommode, Blatt aus einer Folge",
                "author" => "Hoppenhaupt der Ältere, Johann Michael",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Möbel und Hausrat, Rocaille, Kunsthandwerk, Kunstgewerbe, Industriedesign, Kerze, Maske (Maskaron)",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/kommode-blatt-aus-einer-folge/O2014.64/dc00106444",
                "collection" => "Grafische Sammlung",
                "year_from" => "1750",
                "year_to" => "1755",
                "acquisition_date" => "",
                "year" => 1750
            ],
            [
                "id" => "O1896.67",
                "object" => "Ornamentstich",
                "title" => "Runde mit Flechtwerk und Knoten",
                "author" => "Dürer, Albrecht",
                "description" => null,
                "material" => "Papier",
                "technique" => "Holzschnitt",
                "iconography" => "Pflanzenornamente, Flechtwerk (Ornament)",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/runde-mit-flechtwerk-und-knoten/O1896.67/dc00101636",
                "collection" => "Grafische Sammlung",
                "year_from" => "1500",
                "year_to" => "1528",
                "acquisition_date" => "1896",
                "year" => 1500
            ],
            [
                "id" => "O1907.63",
                "object" => "Ornamentstich",
                "title" => "Zwei Säulen mit zahlreichen Ornamenten, Blatt 2 aus der Folge \"Gantz Neu sehr nützl. Säulen und andern Ornamenten\"",
                "author" => "Bergmüller, Johann Andreas / Fridrich der Ältere, Jacob Andreas / Jeremias Wolff Erben",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Säule, Pfeiler (Architektur), Amoretten, Putten, Akanthusornament, Skulptur, Plastik, Bildhauerkunst, Ornamente, Frau, Personifikationen, Maske (Maskaron), Kunst",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/zwei-saulen-mit-zahlreichen-ornamenten-blatt-2-aus-der-folge-gantz-neu-sehr-nutzl-saulen-und-andern-/O1907.63/dc00106299",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730 / 1730 / 1730",
                "year_to" => "1738 / 1740 / 1740",
                "acquisition_date" => "1907",
                "year" => 1730
            ],
            [
                "id" => "EP1986.86",
                "object" => "Plakat",
                "title" => "Irrgarten. Redoute des Neuen Vereins",
                "author" => "Erler, Fritz / Neuer Verein (München) / Oscar Consée",
                "description" => null,
                "material" => "Papier",
                "technique" => "Lithografie",
                "iconography" => "Geschichte des Cupido, Amor (Eros), Laterne, Maske, Kartusche (Ornament), Karneval, Fastnacht, Ball, Tanzveranstaltung",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/irrgarten-redoute-des-neuen-vereins/EP1986.86/mkg-e00109407",
                "collection" => "Plakatsammlung",
                "year_from" => "1905 / 1905 / 1905",
                "year_to" => "1910 / 1910 / 1910",
                "acquisition_date" => "",
                "year" => 1905
            ],
            [
                "id" => "2002.5",
                "object" => "Pelike",
                "title" => "Pelike Form 2 (A: sitzende Nike | B: laufender Jüngling)",
                "author" => "Gioia del Colle-Maler / Trendall, Arthur Dale / Cambitoglou, Alexander",
                "description" => null,
                "material" => "Ton",
                "technique" => "bemalt (Keramik), schnell gedreht, wechselnd gebrannt",
                "iconography" => "Geschichte von Nike, stehende Figur, junger Mann, Jugendlicher, Victoria, Altar, Eierstab, Palmette (Ornament), Mäander, , Schmuckkasten",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/pelike-form-2-a-sitzende-nike-b-laufender-jungling/2002.5/dc00127291",
                "collection" => "Antike",
                "year_from" => "350 v. Chr.",
                "year_to" => "340 v. Chr.",
                "acquisition_date" => "2002",
                "year" => -350
            ],
            [
                "id" => "O1913.165",
                "object" => "Ornamentstich",
                "title" => "Gotische Laubwerkfüllung",
                "author" => "Hopfer, Daniel",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Pflanzenornamente, Rankenornament, Arabeske (Ornament), Vögel",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/gotische-laubwerkfullung/O1913.165/dc00101597",
                "collection" => "Grafische Sammlung",
                "year_from" => "1500",
                "year_to" => "1536",
                "acquisition_date" => "1913",
                "year" => 1500
            ],
            [
                "id" => "O1895.152",
                "object" => "Ornamentstich",
                "title" => "Rocaille-Kartusche, Blatt 2 aus der Folge \"Kartuschen\"",
                "author" => "Kilian, Georg Christoph",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Rocaille, Kartusche (Ornament)",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/rocaille-kartusche-blatt-2-aus-der-folge-kartuschen/O1895.152/dc00104808",
                "collection" => "Grafische Sammlung",
                "year_from" => "1730",
                "year_to" => "1750",
                "acquisition_date" => "",
                "year" => 1730
            ],
            [
                "id" => "JB1891.31",
                "object" => "Ornamentstich",
                "title" => "Standuhr, Nachstich von Blatt 2 der Folge \"Standuhren auf schlanken Kasten\"",
                "author" => "Hoppenhaupt der Ältere, Johann Michael / Hertel der Ältere, Johann Georg",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Zeitmessung/Uhr, Rocaille, Amoretten, Putten, Symbole und Personifikationen des Todes, Leben und Vergänglichkeit des Menschen, Vanitas (christliche Religion), Geschichte des Saturn (Chronos), Sanduhr, Kunsthandwerk, Kunstgewerbe, Industriedesign, Ornament...",
                "style" => "Rokoko",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/standuhr-nachstich-von-blatt-2-der-folge-standuhren-auf-schlanken-kasten/JB1891.31/dc00106446",
                "collection" => "Grafische Sammlung",
                "year_from" => "1750 / 1750",
                "year_to" => "1755 / 1755",
                "acquisition_date" => "1891",
                "year" => 1750
            ],
            [
                "id" => "1893.245",
                "object" => "Astrolabium",
                "title" => "Astrolabium",
                "author" => "Fath Ali Schah",
                "description" => null,
                "material" => "Bronze",
                "technique" => "graviert",
                "iconography" => "Tierkreis, Tierkreiszeichen, Sterne, Sternbilder, Ornamente",
                "style" => "Kadjaren",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/astrolabium/1893.245/dc00119212",
                "collection" => "Islamische Kunst",
                "year_from" => "1801 / 1893",
                "year_to" => "1813",
                "acquisition_date" => "1893",
                "year" => 1801
            ],
            [
                "id" => "1991.76",
                "object" => "Phiale",
                "title" => "Phiale mit Jüngling als Griff (Innen: Frauengemach)",
                "author" => "Baltimore-Maler / Trendall, Arthur Dale / Cambitoglou, Alexander / Schauenburg, Konrad",
                "description" => null,
                "material" => "Ton",
                "technique" => "scheibengedreht, bemalt (Keramik), wechselnd gebrannt",
                "iconography" => "Raub des Ganymed, Schwan, junger Mann, Jugendlicher, Frau, Stuhl, Schmuckkasten, Eierstab, Ornamente",
                "style" => "Spätklassik  (Griechische Antike), Griechische Antike",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/phiale-mit-jungling-als-griff-innen-frauengemach/1991.76/dc00127056",
                "collection" => "Antike",
                "year_from" => "320 v. Chr.",
                "year_to" => "310 v. Chr.",
                "acquisition_date" => "19.04.1991",
                "year" => -320
            ],
            [
                "id" => "O1896.69",
                "object" => "Ornamentstich",
                "title" => "Runde mit Flechtwerk und Knoten",
                "author" => "Dürer, Albrecht",
                "description" => null,
                "material" => "Papier",
                "technique" => "Holzschnitt",
                "iconography" => "Pflanzenornamente, Flechtwerk (Ornament)",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/runde-mit-flechtwerk-und-knoten/O1896.69/dc00101637",
                "collection" => "Grafische Sammlung",
                "year_from" => "1500",
                "year_to" => "1528",
                "acquisition_date" => "1896",
                "year" => 1500
            ],
            [
                "id" => "O2013.5",
                "object" => "Ornamentstich",
                "title" => "Groteske Plafonddekoration",
                "author" => "Hopfer, Daniel",
                "description" => null,
                "material" => "Papier",
                "technique" => "Radierung",
                "iconography" => "Groteske (Ornament), Kandelaber (Ornament), architektonische Details, Innendekoration (eines Hauses), Tiere als Ornament, Tierornamente",
                "style" => "Renaissance",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/groteske-plafonddekoration/O2013.5/dc00101645",
                "collection" => "Grafische Sammlung",
                "year_from" => "1530",
                "year_to" => "1536",
                "acquisition_date" => "1915",
                "year" => 1530
            ],
            [
                "id" => "1910.85",
                "object" => "Schale",
                "title" => "Schale (coppa) mit der Personifikation des Monats April",
                "author" => "Grue, Carlo Antonio / Collaert, Adriaen",
                "description" => null,
                "material" => "Majolika, Keramik",
                "technique" => "scheibengedreht, glasiert, bemalt (Keramik), gebrannt (Keramik), vergoldet",
                "iconography" => "Personifikationen, Monate, Monatsbilder, Garten, Gärten und Parks, Gartenarbeit, April, Fluss, Liebende, Liebespaar, Rankenornament",
                "style" => "Barock",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/schale-coppa-mit-der-personifikation-des-monats-april/1910.85/mkg-e00120360",
                "collection" => "Europäisches Kunsthandwerk und Skulptur",
                "year_from" => "1696",
                "year_to" => "1705",
                "acquisition_date" => "09.01.1910",
                "year" => 1696
            ],
            [
                "id" => "EG2020.38.17",
                "object" => "Entwurfszeichnung",
                "title" => "Blumenornament. Farbiger Entwurf für eine Zierleiste",
                "author" => "Hahn-Brinckmann, Henriette",
                "description" => null,
                "material" => "Papier, Bleistift, Deckende Wasserfarbe",
                "technique" => "Gouache",
                "iconography" => "Blumenornamente",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/blumenornament-farbiger-entwurf-fur-eine-zierleiste/EG2020.38.17/mkg-e00191430",
                "collection" => "Grafische Sammlung",
                "year_from" => "1897",
                "year_to" => "1903",
                "acquisition_date" => "",
                "year" => 1897
            ],
            [
                "id" => "E1967.143",
                "object" => "Druckgrafik",
                "title" => "Odysseus unterm Widder",
                "author" => "Wolff, Gustav Heinrich",
                "description" => null,
                "material" => "Japanpapier",
                "technique" => "Holzschnitt",
                "iconography" => "Odysseus, Klassische Mythologie/Antike Geschichte, Odysseus und seine Begleiter im Land der Zyklopen, Widder (Tier), griechische Schrift, Mäander, Zyklopen",
                "style" => "Klassische Moderne",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/odysseus-unterm-widder/E1967.143/dc00099804",
                "collection" => "Grafische Sammlung",
                "year_from" => "1924 / 1933",
                "year_to" => "1967",
                "acquisition_date" => "1967",
                "year" => 1924
            ],
            [
                "id" => "1982.015",
                "object" => "Stuhl",
                "title" => "Stuhl",
                "author" => "Bugatti, Carlo",
                "description" => null,
                "material" => "Nussbaum, Pergament, Kupfer, Zinn, Knochen",
                "technique" => ", bemalt",
                "iconography" => "Vögel, Sterne, Sternbilder, Ornamente, arabische Schrift",
                "style" => "Jugendstil",
                "web_url" => "https://sammlungonline.mkg-hamburg.de/de/object/stuhl/1982.015/dc00002179",
                "collection" => "Kunstgewerbe und Design",
                "year_from" => "1890",
                "year_to" => "1900",
                "acquisition_date" => "04.1982",
                "year" => 1890
            ]
        ];

        collect($items)->each(function ($item) {
            Item::forceCreate($item);
        });
    }
}
